import { test, expect } from '@playwright/test';
import { LEAF_URLS } from '../leaf_test_utils/leaf_util_methods';

test.describe('QR Code Generation', () => {

  test.use({
    ignoreHTTPSErrors: true
  });

  test('QR code is generated on Request Portal main page', async ({ page }) => {
    await page.goto(LEAF_URLS.PORTAL_HOME);

    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    const qrcodeElement = page.locator('#qrcode-js');
    await expect(qrcodeElement, 'QR code container element should exist on page').toBeAttached();

    // QR code should contain canvas or img element (generated by QRCode.js)
    const qrcodeContent = qrcodeElement.locator('canvas, img').first();
    await expect(qrcodeContent, 'QR code should contain generated canvas or img element').toBeAttached();

    // Verify the QR code canvas exists
    const canvas = qrcodeElement.locator('canvas').first();
    const canvasCount = await canvas.count();
    expect(canvasCount, 'QR code should generate a canvas element').toBeGreaterThan(0);
  });

  test('QR code is generated on Request Portal reports page', async ({ page }) => {
    await page.goto(`https://host.docker.internal/Test_Request_Portal/?a=reports`);

    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    const qrcodeElement = page.locator('#qrcode-js');
    await expect(qrcodeElement, 'QR code container should exist on Request Portal reports page').toBeAttached();

    const qrcodeContent = qrcodeElement.locator('canvas, img').first();
    await expect(qrcodeContent, 'QR code should be generated on Request Portal reports page').toBeAttached();
  });

  test('QR code is generated on Request Portal form page', async ({ page }) => {
    await page.goto(`https://host.docker.internal/Test_Request_Portal/?a=printview`);

    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    const qrcodeElement = page.locator('#qrcode-js');

    // Check if element exists on this page (some pages may not have it)
    const count = await qrcodeElement.count();
    if (count > 0) {
      await expect(qrcodeElement, 'QR code container element should exist on form page').toBeAttached();

      const qrcodeContent = qrcodeElement.locator('canvas, img').first();
      await expect(qrcodeContent, 'QR code should contain generated canvas or img element').toBeAttached();
    } else {
      test.skip();
    }
  });

  test('QR code encodes current page URL', async ({ page }) => {
    const testURL = `https://host.docker.internal/Test_Request_Portal/?a=reports&v=3`;
    await page.goto(testURL);

    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    // Get the actual URL that was loaded
    const actualURL = page.url();

    // Verify QR code was generated
    const qrcodeElement = page.locator('#qrcode-js');
    await expect(qrcodeElement, 'QR code should exist').toBeAttached();

    // Get the title attribute which contains the encoded URL
    const titleAttr = await qrcodeElement.getAttribute('title');
    expect(titleAttr, 'QR code title attribute should contain encoded URL').toBeTruthy();

    // Decode the URL from title attribute (it's URL encoded)
    const decodedURL = decodeURIComponent(titleAttr || '');
    expect(decodedURL, `QR code should encode the current page URL, got: ${decodedURL}`).toContain('host.docker.internal');
    expect(actualURL, `Page URL should contain 'a=reports': ${actualURL}`).toContain('a=reports');

    // Verify QR code generation created canvas and img
    const canvas = qrcodeElement.locator('canvas').first();
    const img = qrcodeElement.locator('img').first();

    const hasCanvas = await canvas.count() > 0;
    const hasImg = await img.count() > 0;

    expect(hasCanvas || hasImg, 'QR code should have generated canvas or img element').toBeTruthy();
  });

  test('QR code has display:none for screen mode', async ({ page }) => {
    await page.goto(LEAF_URLS.PORTAL_HOME);

    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    const qrcodeElement = page.locator('#qrcode-js');
    await expect(qrcodeElement, 'QR code element should exist before checking style').toBeAttached();

    // Verify it has display:none in screen mode
    const styleAttr = await qrcodeElement.getAttribute('style');
    expect(styleAttr, 'QR code should have "display: none" in screen mode to hide on screen').toContain('display: none');
  });

  test('QR code contains both canvas and img elements', async ({ page }) => {
    await page.goto(LEAF_URLS.PORTAL_HOME);

    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    const qrcodeElement = page.locator('#qrcode-js');

    // QRCode.js generates both a canvas (for modern browsers) and img (fallback)
    const canvas = qrcodeElement.locator('canvas');
    const img = qrcodeElement.locator('img');

    await expect(canvas, 'QR code should contain canvas element').toBeAttached();
    await expect(img, 'QR code should contain img element as fallback').toBeAttached();

    // Verify img has base64 data
    const imgSrc = await img.getAttribute('src');
    expect(imgSrc, 'QR code img should have base64 data URL').toContain('data:image/png;base64');
  });

  test('QR code element has title with encoded URL', async ({ page }) => {
    await page.goto(LEAF_URLS.PORTAL_HOME);

    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    const qrcodeElement = page.locator('#qrcode-js');
    await expect(qrcodeElement, 'QR code element should exist').toBeAttached();

    // Check title attribute contains URL-encoded current page
    const title = await qrcodeElement.getAttribute('title');
    expect(title, 'QR code should have title attribute with encoded URL').toBeTruthy();
    expect(title, 'Title should be URL-encoded (contain %2F for /)').toContain('%2F');
  });

  test('QR code regenerates on different pages with different URLs', async ({ page }) => {
    // Navigate to first page
    await page.goto(LEAF_URLS.PORTAL_HOME);
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    const qrcode1 = page.locator('#qrcode-js');
    await expect(qrcode1, 'QR code should exist on first page').toBeAttached();

    const title1 = await qrcode1.getAttribute('title');

    // Navigate to different page
    await page.goto(`https://host.docker.internal/Test_Request_Portal/?a=reports`);
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    const qrcode2 = page.locator('#qrcode-js');
    await expect(qrcode2, 'QR code should exist on second page').toBeAttached();

    const title2 = await qrcode2.getAttribute('title');

    // Titles should be different (different URLs)
    expect(title1, 'First and second page should have different QR code URLs').not.toBe(title2);

    // Decode and check the URL contains a=reports
    const decodedTitle2 = decodeURIComponent(title2 || '');
    expect(decodedTitle2, `Second page QR code should encode URL with a=reports, got: ${decodedTitle2}`).toContain('a=reports');
  });
});